# Generated by Django 3.2.18 on 2023-04-21 16:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='link',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='price',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time_mintues',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='title',
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='الوصف (Arabic)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='description (English)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_ar',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path, verbose_name='الصورة (Arabic)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_en',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path, verbose_name='image (English)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='link_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='الرابط (Arabic)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='link_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='link (English)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='price_ar',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='التكلفة (Arabic)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='price_en',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='price (English)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_minutes_ar',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='الوقت بالدقائق(Arabic)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_minutes_en',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='time_minutes (English)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_ar',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='اسم الوصفة (Arabic)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_en',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='title (English)'),
        ),
    ]
