# Generated by Django 3.2.18 on 2023-04-22 08:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230421_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'الوصفة', 'verbose_name_plural': 'الوصفات'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image_ar',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image_en',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path, verbose_name='الصورة'),
        ),
    ]
